// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/user.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface Empty {
}

export interface User {
  id: string;
  username: string;
  password: string;
  role: string;
  biBan: boolean;
  vang: number;
  ngoc: number;
  sucManh: number;
  vangNapTuWeb: number;
  ngocNapTuWeb: number;
  x: number;
  y: number;
  mapHienTai: string;
  daVaoTaiKhoanLanDau: boolean;
  coDeTu: boolean;
  danhSachVatPhamWeb: number[];
}

export interface RegisterRequest {
  username: string;
  password: string;
}

export interface RegisterResponse {
  success: boolean;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  access_token: string;
}

export interface TokenRequest {
  token: string;
}

export interface GetUserRequest {
  username: string;
}

export interface UserResponse {
  user: User | undefined;
}

export interface SaveGameRequest {
  user: User | undefined;
  sucManhDeTu: number;
}

export interface SaveGameResponse {
  message: string;
}

export interface UsernameRequest {
  username: string;
}

export interface BalanceResponse {
  vangNapTuWeb: number;
  ngocNapTuWeb: number;
}

export interface UseBalanceRequest {
  username: string;
  amount: number;
}

export interface UpdateBalanceRequest {
  username: string;
  type: string;
  amount: number;
}

export interface AddBalanceRequest {
  username: string;
  amount: number;
}

export interface UserListResponse {
  users: User[];
}

export interface AddItemRequest {
  username: string;
  itemId: number;
}

export interface ItemListResponse {
  itemIds: number[];
}

export interface UseItemRequest {
  username: string;
  itemId: number;
}

export interface BanUserRequest {
  username: string;
  adminName: string;
}

export interface UpdateRoleRequest {
  username: string;
  newRole: string;
  adminName: string;
}

export interface MessageResponse {
  message: string;
}

export const USER_PACKAGE_NAME = "user";

/** ===== SERVICE DEFINITION ===== */

export interface UserServiceClient {
  register(request: RegisterRequest, metadata?: Metadata): Observable<RegisterResponse>;

  login(request: LoginRequest, metadata?: Metadata): Observable<LoginResponse>;

  getProfile(request: TokenRequest, metadata?: Metadata): Observable<UserResponse>;

  saveGame(request: SaveGameRequest, metadata?: Metadata): Observable<SaveGameResponse>;

  getUser(request: GetUserRequest, metadata?: Metadata): Observable<UserResponse>;

  getBalance(request: UsernameRequest, metadata?: Metadata): Observable<BalanceResponse>;

  useVangNapTuWeb(request: UseBalanceRequest, metadata?: Metadata): Observable<BalanceResponse>;

  useNgocNapTuWeb(request: UseBalanceRequest, metadata?: Metadata): Observable<BalanceResponse>;

  updateBalance(request: UpdateBalanceRequest, metadata?: Metadata): Observable<BalanceResponse>;

  addVangNapTuWeb(request: AddBalanceRequest, metadata?: Metadata): Observable<BalanceResponse>;

  addNgocNapTuWeb(request: AddBalanceRequest, metadata?: Metadata): Observable<BalanceResponse>;

  getTop10BySucManh(request: Empty, metadata?: Metadata): Observable<UserListResponse>;

  getTop10ByVang(request: Empty, metadata?: Metadata): Observable<UserListResponse>;

  addItemWeb(request: AddItemRequest, metadata?: Metadata): Observable<MessageResponse>;

  getItemsWeb(request: UsernameRequest, metadata?: Metadata): Observable<ItemListResponse>;

  useItemWeb(request: UseItemRequest, metadata?: Metadata): Observable<MessageResponse>;

  banUser(request: BanUserRequest, metadata?: Metadata): Observable<MessageResponse>;

  unbanUser(request: BanUserRequest, metadata?: Metadata): Observable<MessageResponse>;

  updateRole(request: UpdateRoleRequest, metadata?: Metadata): Observable<MessageResponse>;
}

/** ===== SERVICE DEFINITION ===== */

export interface UserServiceController {
  register(request: RegisterRequest, metadata?: Metadata): Observable<RegisterResponse>;

  login(request: LoginRequest, metadata?: Metadata): Observable<LoginResponse>;

  getProfile(request: TokenRequest, metadata?: Metadata): Observable<UserResponse>;

  saveGame(request: SaveGameRequest, metadata?: Metadata): Observable<SaveGameResponse>;

  getUser(request: GetUserRequest, metadata?: Metadata): Observable<UserResponse>;

  getBalance(request: UsernameRequest, metadata?: Metadata): Observable<BalanceResponse>;

  useVangNapTuWeb(request: UseBalanceRequest, metadata?: Metadata): Observable<BalanceResponse>;

  useNgocNapTuWeb(request: UseBalanceRequest, metadata?: Metadata): Observable<BalanceResponse>;

  updateBalance(request: UpdateBalanceRequest, metadata?: Metadata): Observable<BalanceResponse>;

  addVangNapTuWeb(request: AddBalanceRequest, metadata?: Metadata): Observable<BalanceResponse>;

  addNgocNapTuWeb(request: AddBalanceRequest, metadata?: Metadata): Observable<BalanceResponse>;

  getTop10BySucManh(request: Empty, metadata?: Metadata): Observable<UserListResponse>;

  getTop10ByVang(request: Empty, metadata?: Metadata): Observable<UserListResponse>;

  addItemWeb(request: AddItemRequest, metadata?: Metadata): Observable<MessageResponse>;

  getItemsWeb(request: UsernameRequest, metadata?: Metadata): Observable<ItemListResponse>;

  useItemWeb(request: UseItemRequest, metadata?: Metadata): Observable<MessageResponse>;

  banUser(request: BanUserRequest, metadata?: Metadata): Observable<MessageResponse>;

  unbanUser(request: BanUserRequest, metadata?: Metadata): Observable<MessageResponse>;

  updateRole(request: UpdateRoleRequest, metadata?: Metadata): Observable<MessageResponse>;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "register",
      "login",
      "getProfile",
      "saveGame",
      "getUser",
      "getBalance",
      "useVangNapTuWeb",
      "useNgocNapTuWeb",
      "updateBalance",
      "addVangNapTuWeb",
      "addNgocNapTuWeb",
      "getTop10BySucManh",
      "getTop10ByVang",
      "addItemWeb",
      "getItemsWeb",
      "useItemWeb",
      "banUser",
      "unbanUser",
      "updateRole",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
